[package]
name = "biz-scraping"
version = "0.1.0"
description = "Buscador inteligente de negocios en Google Maps"
authors = ["you"]
edition = "2021"

[lib]
name = "biz_scraping_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.40.1", features = ["bundled"] }
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "mysql"] }
tokio = { version = "1.52.3", features = ["full"] }

