use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};

use rustcraper::types::Config;
use tauri::{AppHandle, Emitter, State};

use crate::persistence::{ConfigStore, SavedConfig};
use crate::verboser::{TauriVerboser, VerboserPayload};

pub struct AppState {
    pub store: Mutex<ConfigStore>,
    pub cancel_flag: Arc<AtomicBool>,
}

impl AppState {
    pub fn new(store: ConfigStore) -> Self {
        Self {
            store: Mutex::new(store),
            cancel_flag: Arc::new(AtomicBool::new(false)),
        }
    }
}

#[tauri::command]
pub fn list_configs(state: State<'_, AppState>) -> Result<Vec<SavedConfig>, String> {
    let store = state.store.lock().map_err(|e| e.to_string())?;
    Ok(store.list())
}

#[tauri::command]
pub fn save_config(
    state: State<'_, AppState>,
    name: String,
    config: Config,
    started: bool,
) -> Result<SavedConfig, String> {
    let store = state.store.lock().map_err(|e| e.to_string())?;
    let saved = store
        .save(&name, config, started)
        .map_err(|e| e.to_string())?;
    store
        .set_last_selected(Some(&saved.id))
        .map_err(|e| e.to_string())?;
    Ok(saved)
}

#[tauri::command]
pub fn delete_config(state: State<'_, AppState>, id: String) -> Result<(), String> {
    let store = state.store.lock().map_err(|e| e.to_string())?;
    store.delete(&id).map_err(|e| e.to_string())?;
    Ok(())
}

#[tauri::command]
pub fn get_last_selected(state: State<'_, AppState>) -> Result<Option<SavedConfig>, String> {
    let store = state.store.lock().map_err(|e| e.to_string())?;
    Ok(store.get_last_selected())
}

#[tauri::command]
pub fn set_last_selected(state: State<'_, AppState>, id: String) -> Result<(), String> {
    let store = state.store.lock().map_err(|e| e.to_string())?;
    store
        .set_last_selected(Some(&id))
        .map_err(|e| e.to_string())?;
    Ok(())
}

#[tauri::command]
pub async fn run_scraping(
    app: AppHandle,
    state: State<'_, AppState>,
    config: Config,
) -> Result<(), String> {
    use std::future::Future;
    /// Wraps a `Future` and marks it as `Send` to work around the limitation
    /// tracked in rust-lang/rust#96865: auto-trait analysis does not
    /// generalize lifetimes in self-referential state machines generated by
    /// `async fn`, even when the concrete types themselves are `Send + Sync`.
    ///
    /// # Safety
    ///
    /// This is sound because we manually verify that NO reference captured by
    /// the state machine points to a non-`Sync` type:
    ///
    /// | Reference in state machine | Type `T` | `T: Sync`? | Justification |
    /// |---|---|---|---|
    /// | `&DbManager` | `DbManager` | Yes | Wrapper around `MySqlPool` (which is `Sync`) |
    /// | `&Path` | `Path` | Yes | Immutable data, inherently `Sync` |
    /// | `&Pool<MySql>` | `MySqlPool` | Yes | Designed by sqlx for multithreaded use |
    ///
    /// All references are shared `&T` references (never `&mut T`), and there
    /// are no `Cell`, `RefCell`, `Rc`, or any other non-`Send` interior
    /// mutability types involved.
    ///
    /// The only `Mutex` present (`AppState.store`) is accessed through Tokio's
    /// async lock, which is `Send`.
    ///
    /// The compiler cannot prove `Send` because it does not connect the
    /// relationship between the `'local` lifetime of each reference and the
    /// corresponding field in the struct generated by the `async` desugaring.
    /// This has been a known limitation since 2022 (rust-lang/rust#96865),
    /// not a genuine data race risk.
    struct SpawnUnsafe<F: Future>(F);
    unsafe impl<F: Future> Send for SpawnUnsafe<F> {}
    impl<F: Future> Future for SpawnUnsafe<F> {
        type Output = F::Output;
        fn poll(
            self: std::pin::Pin<&mut Self>,
            cx: &mut std::task::Context<'_>,
        ) -> std::task::Poll<Self::Output> {
            unsafe { self.map_unchecked_mut(|s| &mut s.0).poll(cx) }
        }
    }

    state.cancel_flag.store(false, Ordering::SeqCst);
    let cancel_flag = state.cancel_flag.clone();
    let app_handle = app.clone();

    let future = SpawnUnsafe(async move {
        app_handle.emit("scraping-started", ()).ok();
        let verboser = TauriVerboser::new(app, cancel_flag);
        if let Err(e) = rustcraper::engine::run(config, verboser).await {
            app_handle
                .emit(
                    "verboser-event",
                    VerboserPayload {
                        kind: "error".to_string(),
                        message: format!("Error durante scraping: {e}"),
                    },
                )
                .ok();
        }
        app_handle.emit("scraping-finished", ()).ok();
    });

    tauri::async_runtime::spawn(future);
 
    Ok(())
}

#[tauri::command]
pub fn cancel_scraping(state: State<'_, AppState>) -> Result<(), String> {
    state.cancel_flag.store(true, Ordering::SeqCst);
    Ok(())
}
