use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};

use rustcrape::types::Config;
use serde::{Deserialize, Serialize};
use tauri::{AppHandle, Emitter, State};
use tauri_plugin_dialog::{DialogExt, FilePath};

use crate::persistence::{ConfigStore, GlobalSettings, SavedConfig};
use crate::verboser::{TauriVerboser, VerboserPayload};

pub struct AppState {
    pub store: Mutex<ConfigStore>,
    pub cancel_flag: Arc<AtomicBool>,
}

impl AppState {
    pub fn new(store: ConfigStore) -> Self {
        Self {
            store: Mutex::new(store),
            cancel_flag: Arc::new(AtomicBool::new(false)),
        }
    }
}

#[tauri::command]
pub fn list_configs(state: State<'_, AppState>) -> Result<Vec<SavedConfig>, String> {
    let store = state.store.lock().map_err(|e| e.to_string())?;
    Ok(store.list())
}

#[tauri::command]
pub fn save_config(
    state: State<'_, AppState>,
    name: String,
    config: Config,
    started: bool,
) -> Result<SavedConfig, String> {
    let store = state.store.lock().map_err(|e| e.to_string())?;
    let saved = store
        .save(&name, config, started)
        .map_err(|e| e.to_string())?;
    store
        .set_last_selected(Some(&saved.id))
        .map_err(|e| e.to_string())?;
    Ok(saved)
}

#[tauri::command]
pub fn delete_config(state: State<'_, AppState>, id: String) -> Result<(), String> {
    let store = state.store.lock().map_err(|e| e.to_string())?;
    store.delete(&id).map_err(|e| e.to_string())?;
    Ok(())
}

#[tauri::command]
pub fn get_last_selected(state: State<'_, AppState>) -> Result<Option<SavedConfig>, String> {
    let store = state.store.lock().map_err(|e| e.to_string())?;
    Ok(store.get_last_selected())
}

#[tauri::command]
pub fn set_last_selected(state: State<'_, AppState>, id: String) -> Result<(), String> {
    let store = state.store.lock().map_err(|e| e.to_string())?;
    store
        .set_last_selected(Some(&id))
        .map_err(|e| e.to_string())?;
    Ok(())
}

#[tauri::command]
pub fn load_global_settings(state: State<'_, AppState>) -> Result<GlobalSettings, String> {
    let store = state.store.lock().map_err(|e| e.to_string())?;
    store.load_global_settings().map_err(|e| e.to_string())
}

#[tauri::command]
pub fn save_global_settings(
    state: State<'_, AppState>,
    settings: GlobalSettings,
) -> Result<(), String> {
    let store = state.store.lock().map_err(|e| e.to_string())?;
    store.save_global_settings(&settings).map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn run_scraping(
    app: AppHandle,
    state: State<'_, AppState>,
    config: Config,
) -> Result<(), String> {
    use std::future::Future;
    /// Wraps a `Future` and marks it as `Send` to work around the limitation
    /// tracked in rust-lang/rust#96865: auto-trait analysis does not
    /// generalize lifetimes in self-referential state machines generated by
    /// `async fn`, even when the concrete types themselves are `Send + Sync`.
    ///
    /// # Safety
    ///
    /// This is sound because we manually verify that NO reference captured by
    /// the state machine points to a non-`Sync` type:
    ///
    /// | Reference in state machine | Type `T` | `T: Sync`? | Justification |
    /// |---|---|---|---|
    /// | `&DbManager` | `DbManager` | Yes | Wrapper around `MySqlPool` (which is `Sync`) |
    /// | `&Path` | `Path` | Yes | Immutable data, inherently `Sync` |
    /// | `&Pool<MySql>` | `MySqlPool` | Yes | Designed by sqlx for multithreaded use |
    ///
    /// All references are shared `&T` references (never `&mut T`), and there
    /// are no `Cell`, `RefCell`, `Rc`, or any other non-`Send` interior
    /// mutability types involved.
    ///
    /// The only `Mutex` present (`AppState.store`) is accessed through Tokio's
    /// async lock, which is `Send`.
    ///
    /// The compiler cannot prove `Send` because it does not connect the
    /// relationship between the `'local` lifetime of each reference and the
    /// corresponding field in the struct generated by the `async` desugaring.
    /// This has been a known limitation since 2022 (rust-lang/rust#96865),
    /// not a genuine data race risk.
    struct SpawnUnsafe<F: Future>(F);
    unsafe impl<F: Future> Send for SpawnUnsafe<F> {}
    impl<F: Future> Future for SpawnUnsafe<F> {
        type Output = F::Output;
        fn poll(
            self: std::pin::Pin<&mut Self>,
            cx: &mut std::task::Context<'_>,
        ) -> std::task::Poll<Self::Output> {
            unsafe { self.map_unchecked_mut(|s| &mut s.0).poll(cx) }
        }
    }

    state.cancel_flag.store(false, Ordering::SeqCst);
    let cancel_flag = state.cancel_flag.clone();
    let app_handle = app.clone();

    let future = SpawnUnsafe(async move {
        app_handle.emit("scraping-started", ()).ok();
        let verboser = TauriVerboser::new(app, cancel_flag);
        if let Err(e) = rustcrape::engine::run(config, verboser).await {
            app_handle
                .emit(
                    "verboser-event",
                    VerboserPayload {
                        kind: "error".to_string(),
                        message: format!("Error durante scraping: {e}"),
                    },
                )
                .ok();
        }
        app_handle.emit("scraping-finished", ()).ok();
    });

    tauri::async_runtime::spawn(future);

    Ok(())
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Announcement {
    pub title: String,
    pub content: String,
    pub link: String,
    pub link_label: String,
    pub closeable: bool,
}

#[tauri::command]
pub async fn check_announcement() -> Option<Announcement> {
    let version = env!("CARGO_PKG_VERSION");
    let url = "https://raw.githubusercontent.com/rubcc95/rustcrape/refs/heads/main/other_file";

    let resp = reqwest::get(url).await.ok()?;
    let body = resp.text().await.ok()?;
    let json: serde_json::Value = serde_json::from_str(&body).ok()?;
    let entry = json.get(version)?.clone();
    serde_json::from_value(entry).ok()
}

#[tauri::command]
pub fn cancel_scraping(state: State<'_, AppState>) -> Result<(), String> {
    state.cancel_flag.store(true, Ordering::SeqCst);
    Ok(())
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExecutablePickedPayload {
    pub key: String,
    pub path: Option<String>,
}

#[tauri::command]
pub async fn pick_executable(app: AppHandle, key: String) -> Result<(), String> {
    #[cfg(not(windows))]
    let dialog = app.dialog().file();

    #[cfg(windows)]
    let dialog = app.dialog().file().add_filter("exe", &["exe"]);

    let dialog_key = key.clone();

    dialog.pick_file(move |file| {
        fn is_exe(file: Option<FilePath>) -> Option<String> {
            if let Some(file) = file {
                if let Some(path) = file.as_path() {
                    #[cfg(unix)]
                    {
                        use std::os::unix::fs::PermissionsExt;
                        if !std::fs::metadata(path)
                            .is_ok_and(|m| m.permissions().mode() & 0o111 != 0)
                        {
                            return None;
                        }
                    }
                    return Some(path.to_string_lossy().to_string());
                }
            }
            None
        }

        let exe_path = is_exe(file);
        app.emit("executable-picked", ExecutablePickedPayload {
            key: dialog_key,
            path: exe_path,
        }).ok();
    });

    Ok(())
}

// fn is_executable(path: &Path) -> bool {
//     if !path.is_file() {
//         return false;
//     }
//     #[cfg(unix)]
//     {
//         use std::os::unix::fs::PermissionsExt;
//         std::fs::metadata(path)
//             .map(|m| m.permissions().mode() & 0o111 != 0)
//             .unwrap_or(false)
//     }
//     #[cfg(not(unix))]
//     {
//         path.extension()
//             .and_then(|ext| ext.to_str())
//             .is_some_and(|ext| matches!(ext.to_lowercase().as_str(), "exe" | "com" | "bat" | "cmd"))
//     }
// }
